In [1]:
import os
import sys
from pathlib import Path
ROOT = Path('..').absolute()
os.chdir(ROOT)
sys.path.append(str(ROOT))

print(os.getcwd())

c:\Users\YuMeow\WorkSpace\42-MySRAgent

In [2]:
import json
import pandas as pd

df_list = []
for exp_path in sorted(Path("logs/bench_sr_agent/bench_my_sr_agent/results/").glob('*.jsonl'), key=lambda x: x.stem):
    lines = [json.loads(line) for line in exp_path.read_text(encoding="utf-8").splitlines() if line.strip()]
    successful_lines = [line for line in lines if 'error' not in line]
    result = successful_lines[-1] if successful_lines else lines[-1]
    df_list.append(result)
df_results = pd.DataFrame(df_list)

df_id = pd.DataFrame(df_results.pop('id_metrics').tolist(), index=df_results.index).add_prefix('id_')
df_results = df_results.join(df_id)

df_ood = pd.DataFrame(df_results.pop('ood_metrics').tolist(), index=df_results.index).add_prefix('ood_')
df_results = df_results.join(df_ood)

df_results

,equation_id,dataset_identifier,gt_expression,discovered_expression,num_train,num_test,search_time,symbolic_acc,id_mse,id_nmse,id_r2,id_acc01,id_kdt,id_mape,id_num_valid_points,ood_0
0,I.10.7_1_0,lsrtransform,-c*sqrt(1 - m_0**2/m**2),-c * sqrt(1 - (m_0 / m) ** 2),50038,12509,285.780009,False,1.186180e-12,2.868966e-13,1.000000,1.00000,1.000000,1.653165e-06,12509,None
1,I.11.19_0_0,lsrtransform,(A + x2*y2 + x3*y3)/y1,A / y1 + x2 * y2 / y1 + x3 * y3 / y1,80000,20000,468.397883,False,9.653734e-13,6.486476e-15,1.000000,1.00000,1.000000,3.337723e-08,20000,None
2,I.11.19_1_0,lsrtransform,(-A + x1*y1 - x3*y3)/y2,-15.137198565840997 * 1 + -1.435173928124234 *...,80000,20000,471.514486,False,3.736915e-01,4.037515e-03,0.995962,0.86020,0.965402,2.557001e-01,20000,None
3,I.11.19_2_0,lsrtransform,(-A + x1*y1 - x2*y2)/y3,x1 * y1 / y3 - (x2 * y2 + A) / y3,80000,20000,596.509232,False,5.714315e-13,6.224127e-15,1.000000,1.00000,1.000000,5.600253e-08,20000,None
4,I.11.19_3_0,lsrtransform,(A + x2*y2 + x3*y3)/x1,(A + x2 * y2 + x3 * y3) / x1,80000,20000,597.517559,False,9.934709e-13,6.551420e-15,1.000000,1.00000,1.000000,3.364354e-08,20000,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,III.21.20_2_0,lsrtransform,-j*m/(q*rho_c_0),-m * j / (rho_c_0 * q),80000,20000,560.902404,False,3.522013e-12,6.233403e-15,1.000000,1.00000,1.000000,4.629259e-08,20000,None
107,III.21.20_3_0,lsrtransform,-A_vec*q*rho_c_0/j,-rho_c_0 * q * A_vec / j,80000,20000,89.628063,False,9.147218e-14,3.977769e-15,1.000000,1.00000,1.000000,4.668175e-08,20000,None
108,III.4.33_3_0,lsrtransform,h*omega/(2*pi*kb*log(1 + h*omega/(2*pi*E_n))),1.0027535830708822 * E_n / kb + 0.073691851551...,80000,20000,252.713790,False,2.558320e-04,1.669060e-05,0.999983,0.99185,0.998132,4.462638e-03,20000,None
109,III.9.52_0_0,lsrtransform,h*prob*t*(omega - omega_0)**2/(4*pi*Ef*(1 - co...,-1255154.5671792359 * 1 + 226561.3850197006 * ...,80000,20000,235.347465,False,1.929983e+13,1.010160e+00,-0.010160,0.00010,0.263906,1.946790e+05,20000,None
110,III.9.52_1_0,lsrtransform,h*prob*t*(omega - omega_0)**2/(4*pi*p_d*(1 - c...,-1255154.5671792359 * 1 + 226561.3850197006 * ...,80000,20000,494.049538,False,1.929983e+13,1.010160e+00,-0.010160,0.00010,0.263906,1.946790e+05,20000,None

In [3]:
df_results[df_results['id_nmse'] < 1e-7].head(20)[['gt_expression', 'discovered_expression', 'id_mse', 'id_nmse', 'id_r2']].to_dict(orient='records')

[{'gt_expression': '-c*sqrt(1 - m_0**2/m**2)',
  'discovered_expression': '-c * sqrt(1 - (m_0 / m) ** 2)',
  'id_mse': 1.186179604838356e-12,
  'id_nmse': 2.868965920266257e-13,
  'id_r2': 0.9999999999997131},
 {'gt_expression': '(A + x2*y2 + x3*y3)/y1',
  'discovered_expression': 'A / y1 + x2 * y2 / y1 + x3 * y3 / y1',
  'id_mse': 9.653733565080772e-13,
  'id_nmse': 6.48647610799236e-15,
  'id_r2': 0.9999999999999936},
 {'gt_expression': '(-A + x1*y1 - x2*y2)/y3',
  'discovered_expression': 'x1 * y1 / y3 - (x2 * y2 + A) / y3',
  'id_mse': 5.714314873132767e-13,
  'id_nmse': 6.2241271577015845e-15,
  'id_r2': 0.9999999999999938},
 {'gt_expression': '(A + x2*y2 + x3*y3)/x1',
  'discovered_expression': '(A + x2 * y2 + x3 * y3) / x1',
  'id_mse': 9.934709168225883e-13,
  'id_nmse': 6.5514204941579835e-15,
  'id_r2': 0.9999999999999934},
 {'gt_expression': '(-A + x1*y1 - x3*y3)/x2',
  'discovered_expression': '(x1 * y1 - x3 * y3 - A) / x2',
  'id_mse': 5.679918148415428e-13,
  'id_nmse': 6.06727087639076e-15,
  'id_r2': 0.9999999999999939},
 {'gt_expression': '(-A + x1*y1 - x2*y2)/x3',
  'discovered_expression': '(x1 * y1 - A - x2 * y2) / x3',
  'id_mse': 5.809720552347479e-13,
  'id_nmse': 6.3262994221442655e-15,
  'id_r2': 0.9999999999999937},
 {'gt_expression': '-sqrt(q1*q2/(F*epsilon))/(2*sqrt(pi))',
  'discovered_expression': '-sqrt(q1 * q2 / (12.566370614359172 * epsilon * F))',
  'id_mse': 2.8549910431550674e-15,
  'id_nmse': 2.5136330366755035e-15,
  'id_r2': 0.9999999999999974},
 {'gt_expression': '-sqrt(q1/(Ef*epsilon))/(2*sqrt(pi))',
  'discovered_expression': '-sqrt(q1 / (12.566370614 * epsilon * Ef))',
  'id_mse': 2.27867294744235e-15,
  'id_nmse': 2.62495318878403e-15,
  'id_r2': 0.9999999999999973},
 {'gt_expression': '-c*p*sqrt(1/(c**2*m_0**2 + p**2))',
  'discovered_expression': '-1 / sqrt((m_0 / p) ** 2 + 1 / c ** 2)',
  'id_mse': 8.382128173587436e-15,
  'id_nmse': 5.6772493271833215e-15,
  'id_r2': 0.9999999999999943},
 {'gt_expression': 'sqrt(4*E_n/m - omega**2*x**2)/x',
  'discovered_expression': 'sqrt(E_n / m * 3.9999974 / x ** 1.9999981 - omega ** 2)',
  'id_mse': 5.780168591128743e-12,
  'id_nmse': 7.904069382790153e-13,
  'id_r2': 0.9999999999992096},
 {'gt_expression': 'd2/foc - d2/d1',
  'discovered_expression': 'd2 * (d1 - foc) / (foc * d1)',
  'id_mse': 4.01019230573258e-14,
  'id_nmse': 3.6601416178352545e-15,
  'id_r2': 0.9999999999999963},
 {'gt_expression': 'x2*cos(theta1 - theta2) - sqrt(x**2 + x2**2*cos(theta1 - theta2)**2 - x2**2)',
  'discovered_expression': 'x2 * cos(theta1 - theta2) - sqrt(abs(x ** 2 - x2 ** 2 * sin(theta1 - theta2) ** 2))',
  'id_mse': 1.6845435131815617e-13,
  'id_nmse': 1.501686643740824e-14,
  'id_r2': 0.999999999999985},
 {'gt_expression': 'x1*cos(theta1 - theta2) - sqrt(x**2 + x1**2*cos(theta1 - theta2)**2 - x1**2)',
  'discovered_expression': '(x1 ** 2 - x ** 2) / (x1 * cos(theta2 - theta1) + sqrt(x ** 2 - x1 ** 2 * sin(theta2 - theta1) ** 2))',
  'id_mse': 1.6845435124163323e-13,
  'id_nmse': 1.50168664305866e-14,
  'id_r2': 0.999999999999985},
 {'gt_expression': 'sqrt(3)*sqrt(Pwr/(c*epsilon))*(-omega**2 + omega_0**2)/(2*sqrt(pi)*Ef*omega**2)',
  'discovered_expression': 'sqrt(-39.373493745180106 * Pwr / (49.879432974818755 * -3.3065192522545863 * epsilon * c * Ef ** 2)) * abs(omega_0 ** 2 - omega ** 2) / omega ** 2',
  'id_mse': 1.4821226957205731e-12,
  'id_nmse': 2.4950217000221786e-14,
  'id_r2': 0.999999999999975},
 {'gt_expression': 'sqrt(6)*sqrt(pi)*sqrt(Pwr*c**3*epsilon)/a',
  'discovered_expression': 'sqrt(18.84955592153876 * epsilon * c ** 3 * Pwr) / a',
  'id_mse': 6.113441747415258e-12,
  'id_nmse': 6.835808210369742e-15,
  'id_r2': 0.9999999999999931},
 {'gt_expression': 'c*omega*sqrt(1 - v**2/c**2)/(c + v)',
  'discovered_expression': 'omega / sqrt(1 - (v / c) ** 2) - omega * v / c / sqrt(1 - (v / c) ** 2)',
  'id_mse': 3.341224503711402e-14,
  'id_nmse': 7.556102957771666e-15,
  'id_r2': 0.9999999999999925},
 {'gt_expression': 'omega*(c - v)/c',
  'discovered_expression': 'omega * (c - v) / c',
  'id_mse': 4.368002027284165e-14,
  'id_nmse': 7.423548995234065e-15,
  'id_r2': 0.9999999999999926},
 {'gt_expression': 'T*kb*log(n_0/n)/(m*x)',
  'discovered_expression': '1.0000000017925066 * kb * T / (m * x) * log(n_0 / n)',
  'id_mse': 2.438605598627472e-14,
  'id_nmse': 4.692690977700496e-15,
  'id_r2': 0.9999999999999953},
 {'gt_expression': '1 + kb*v/(A*kappa)',
  'discovered_expression': 'kb * v / (kappa * A) + 1',
  'id_mse': 7.273393864085201e-14,
  'id_nmse': 3.6227449264254954e-15,
  'id_r2': 0.9999999999999963},
 {'gt_expression': 'A*kappa*(gamma - 1)/kb',
  'discovered_expression': 'kappa / kb * (gamma - 1) * A',
  'id_mse': 3.3013335289656497e-12,
  'id_nmse': 7.361113848520866e-15,
  'id_r2': 0.9999999999999927}]

In [4]:
import json
import pandas as pd

df_list = []
for exp_path in sorted(Path("logs/bench_sr_agent/bench_my_sr_agent/experiments/").glob('*/result.jsonl'), key=lambda x: x.stem):
    dirname = exp_path.parent.name
    detail = json.loads(exp_path.read_text(encoding="utf-8").strip())
    detail['dirname'] = dirname
    df_list.append(detail)
df_details = pd.DataFrame(df_list)
df_details['token_usage'] = df_details['token_usage'].str.removesuffix('token').str.replace(' k', 'e3').map(float)
df_details['money_usage'] = df_details['money_usage'].str.removesuffix('$').str.replace(' m', 'e-3').str.replace(' μ', 'e-6').map(float)
df_details

,start_time,problem_name,duration_seconds,best_formula,best_mse,status,progress,token_usage,money_usage,tools_usage,llm_model,best_rmse,best_mae,best_r2,times_usage,dirname,error
0,2026-05-25 19:10:37,I.10.7_1_0,285.859445,-c * sqrt(1 - (m_0 / m) ** 2),2.329631e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),254000.0,0.02460,36 call (evaluate_formula=13 call[36%]; code_e...,deepseek/deepseek-v4-flash @ openrouter,4.826626e-07,2.554448e-07,1.000000,4.76 min (request_llm=13.9 s/iter[97%]; get_re...,I.10.7_1_0_20260525_191037,NaN
1,2026-05-25 18:19:05,I.11.19_0_0,468.448895,A / y1 + x2 * y2 / y1 + x3 * y3 / y1,9.653122e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),308000.0,0.03020,55 call (code_executor=19 call[35%]; evaluate_...,deepseek/deepseek-v4-flash @ openrouter,9.825030e-07,6.813457e-07,1.000000,7.81 min (request_llm=20.6 s/iter[88%]; get_re...,I.11.19_0_0_20260525_181905,NaN
2,2026-05-25 20:29:51,I.11.19_1_0,471.479755,-15.137198565840997 * 1 + -1.435173928124234 *...,3.915636e-01,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),322000.0,0.03650,51 call (statistics_analysis=19 call[37%]; cod...,deepseek/deepseek-v4-flash @ openrouter,6.257504e-01,4.547761e-01,0.995753,7.86 min (request_llm=22.3 s/iter[95%]; get_re...,I.11.19_1_0_20260525_202951,NaN
3,2026-05-25 14:04:01,I.11.19_2_0,596.920197,x1 * y1 / y3 - (x2 * y2 + A) / y3,5.761264e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),362000.0,0.02900,59 call (code_executor=21 call[36%]; evaluate_...,deepseek/deepseek-v4-flash @ openrouter,7.590299e-07,5.146607e-07,1.000000,9.94 min (request_llm=25.9 s/iter[87%]; get_re...,I.11.19_2_0_20260525_140401,NaN
4,2026-05-25 19:42:35,I.11.19_3_0,598.380188,(A + x2 * y2 + x3 * y3) / x1,9.802123e-13,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),335000.0,0.03010,56 call (statistics_analysis=20 call[36%]; cod...,deepseek/deepseek-v4-flash @ openrouter,9.900567e-07,6.868412e-07,1.000000,9.96 min (request_llm=27.9 s/iter[93%]; get_re...,I.11.19_3_0_20260525_194235,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,2026-05-25 18:57:54,III.21.20_2_0,561.234369,-m * j / (rho_c_0 * q),3.706815e-12,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),257000.0,0.02710,50 call (evaluate_formula=22 call[44%]; code_e...,deepseek/deepseek-v4-flash @ openrouter,1.925309e-06,1.002608e-06,1.000000,9.35 min (request_llm=21.6 s/iter[77%]; get_re...,III.21.20_2_0_20260525_185754,NaN
118,2026-05-25 20:06:11,III.21.20_3_0,90.074005,-rho_c_0 * q * A_vec / j,1.094244e-13,failed,(R=1/2) × (C=2/2) × (L=2/5) × (K=2),78700.0,0.00551,18 call (evaluate_formula=7 call[39%]; statist...,deepseek/deepseek-v4-flash @ openrouter,3.307935e-07,7.639947e-08,1.000000,1.49 min (request_llm=8.27 s/iter[65%]; get_re...,III.21.20_3_0_20260525_200611,"AttributeError(""'str' object has no attribute ..."
119,2026-05-25 20:25:38,III.4.33_3_0,253.085938,1.0027535830708822 * E_n / kb + 0.073691851551...,2.174935e-04,failed,(R=2/2) × (C=1/2) × (L=1/5) × (K=2),181000.0,0.01860,32 call (code_executor=13 call[41%]; statistic...,deepseek/deepseek-v4-flash @ openrouter,1.474766e-02,7.813426e-03,0.999986,4.21 min (request_llm=22.5 s/iter[98%]; get_re...,III.4.33_3_0_20260525_202538,"AttributeError(""'str' object has no attribute ..."
120,2026-05-25 11:02:12,III.9.52_0_0,236.278131,-1255154.5671792359 * 1 + 226561.3850197006 * ...,4.782640e+14,failed,(R=1/2) × (C=2/2) × (L=3/5) × (K=2),125000.0,0.01190,20 call (code_executor=9 call[45%]; statistics...,deepseek/deepseek-v4-flash @ openrouter,2.186925e+07,4.347542e+05,0.000474,3.92 min (request_llm=28.7 s/iter[98%]; get_re...,III.9.52_0_0_20260525_110212,"AttributeError(""'str' object has no attribute ..."
121,2026-05-25 20:46:13,III.9.52_1_0,494.598074,-1255154.5671792359 * 1 + 226561.3850197006 * ...,4.782640e+14,completed,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),641000.0,0.05360,48 call (code_executor=28 call[58%]; statistic...,deepseek/deepseek-v4-flash @ openrouter,2.186925e+07,4.347542e+05,0.000474,8.23 min (request_llm=23.9 s/iter[97%]; get_re...,III.9.52_1_0_20260525_204613,NaN

In [5]:
df_details['status'].value_counts()

status
completed    90
failed       32
Name: count, dtype: int64

In [6]:
df_details[['token_usage', 'money_usage']].agg(['mean', 'sum'])

      token_usage  money_usage
mean     264265.0     0.023705
sum    32240330.0     2.891995

In [7]:
df_details[df_details['best_rmse'] < 1e-6].merge(df_results[['equation_id', 'gt_equation']], left_on='problem_id', right_on='equation_id')[['problem_id', 'gt_equation', 'best_equation', 'token_usage', 'money_usage']]

KeyError: "['gt_equation'] not in index"

In [ ]:
import json
import pandas as pd

df_list = []
for exp_path in sorted(Path("logs/bench_sr_agent/bench_my_sr_agent/experiments/").glob('*/tool_calls.jsonl'), key=lambda x: x.stem):
    dirname = exp_path.parent.name
    tool_calls = [json.loads(line) for line in exp_path.read_text(encoding="utf-8").splitlines() if line.strip()]
    for call in tool_calls:
        call['dirname'] = dirname
    df_list.extend(tool_calls)
df_tool_calls = pd.DataFrame(df_list)
df_tool_calls

,progress,name,params,ok,result,result_str,meta_data,dirname
0,(R=1/2) × (C=1/2) × (L=1/5) × (K=2),statistics_analysis,"{'variables': ['m', 'm_0', 'c', 'v']}",True,"{'statistics': {'m': {'n_samples': 50038, 'min...","Variable 'm': n=50038, min=1.0350, max=6.3547,...","{'timestamp': 1779707445.8394384, 'execution_t...",I.10.7_1_0_20260525_191037
1,(R=1/2) × (C=1/2) × (L=1/5) × (K=2),statistics_analysis,"{'variables': ['m', 'm_0', 'c', 'v']}",True,"{'statistics': {'m': {'n_samples': 50038, 'min...","Variable 'm': n=50038, min=1.0350, max=6.3547,...","{'timestamp': 1779707445.8458998, 'execution_t...",I.10.7_1_0_20260525_191037
2,(R=1/2) × (C=1/2) × (L=2/5) × (K=2),evaluate_formula,{'f': 'c * sqrt(1 - (m_0/m)**2)'},True,"{'formula': 'c * sqrt(1 - (m_0 / m) ** 2)', 'm...","{'formula': 'c * sqrt(1 - (m_0 / m) ** 2)', 'm...","{'timestamp': 1779707471.9205372, 'execution_t...",I.10.7_1_0_20260525_191037
3,(R=1/2) × (C=1/2) × (L=2/5) × (K=2),evaluate_formula,"{'f': '-c * sqrt(1 - (m_0/m)**2)', 'y': 'v'}",True,"{'formula': '-c * sqrt(1 - (m_0 / m) ** 2)', '...","{'formula': '-c * sqrt(1 - (m_0 / m) ** 2)', '...","{'timestamp': 1779707471.9310975, 'execution_t...",I.10.7_1_0_20260525_191037
4,(R=1/2) × (C=1/2) × (L=3/5) × (K=2),submit_formula,"{'f': '-c * sqrt(1 - (m_0/m)**2)', 'y': 'v'}",True,"{'formula': '-c * sqrt(1 - (m_0 / m) ** 2)', '...","{'formula': '-c * sqrt(1 - (m_0 / m) ** 2)', '...","{'timestamp': 1779707479.9616277, 'execution_t...",I.10.7_1_0_20260525_191037
...,...,...,...,...,...,...,...,...
5171,(R=2/2) × (C=2/2) × (L=4/5) × (K=2),code_executor,"{'program': 'import sys, json, math data_dict ...",True,"{'success': True, 'output': 'Scale=0.5: Mean r...","{'success': True, 'output': 'Scale=0.5: Mean r...","{'timestamp': 1779713651.1248488, 'execution_t...",III.9.52_1_0_20260525_204613
5172,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),call_sindy,"{'x': ['prob', 'p_d', 't', 'h', 'omega', 'omeg...",True,{'formula': '-121638.02 + 2052.672 * prob - 11...,"SINDy result (method=SINDy, config={'poly_degr...","{'timestamp': 1779713667.128187, 'execution_ti...",III.9.52_1_0_20260525_204613
5173,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),call_sindy,"{'x': ['prob', 'p_d', 't', 'h', 'omega', 'omeg...",True,{'formula': '41535.195 + 213.398 * prob - 2852...,"SINDy result (method=SINDy, config={'poly_degr...","{'timestamp': 1779713667.396281, 'execution_ti...",III.9.52_1_0_20260525_204613
5174,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),call_sindy,"{'x': ['prob', 'p_d', 't', 'h', 'omega', 'omeg...",True,{'formula': '-121638.02 + 2052.672 * prob - 11...,"SINDy result (method=SINDy, config={'poly_degr...","{'timestamp': 1779713667.423386, 'execution_ti...",III.9.52_1_0_20260525_204613
5175,(R=2/2) × (C=2/2) × (L=5/5) × (K=2),call_sindy,"{'x': ['prob', 'p_d', 't', 'h', 'omega', 'omeg...",True,{'formula': '41535.195 + 213.398 * prob - 2852...,"SINDy result (method=SINDy, config={'poly_degr...","{'timestamp': 1779713667.5580072, 'execution_t...",III.9.52_1_0_20260525_204613

In [11]:
from bench_sr_agent import DATASET_SPLITS, load_problems, build_argparser

parser = build_argparser()
args, _ = parser.parse_known_args()

datasets = list(DATASET_SPLITS.keys())
problems = []
for dataset in datasets:
    problems.extend(load_problems(dataset, args.data_root))

In [14]:
problems[0]

Problem(dataset_identifier='lsrtransform', equation_idx='II.6.15b_1_0', symbols=['p_d', 'Ef', 'epsilon', 'theta', 'r'], symbol_descs=['the dipole moment', 'the electric field', 'the electric constant or permittivity of the medium', 'the angle between the dipole axis and the position vector', 'the distance from the dipole to the point where the electric field is being measured'], symbol_properties=['O', 'V', 'V', 'V', 'V'], expression='8*pi*Ef*epsilon*r**3/(3*sin(2*theta))', samples={'test': array([[-1.89978886e+01,  5.25637604e-02,  1.82653153e+00,
         2.89664268e+00,  2.23163176e+00],
       [-3.33039780e+01, -1.37035444e-01,  2.89017677e+00,
         1.25211060e+00,  1.81440020e+00],
       [-1.55860071e+01,  8.87142196e-02,  2.63639474e+00,
         2.06723142e+00,  1.88169527e+00],
       ...,
       [-7.01482487e+00,  1.20707955e-02,  2.59601259e+00,
         1.96577024e+00,  2.66748810e+00],
       [-2.04217935e+00, -3.72400843e-02,  1.98443580e+00,
         1.00902021e+00,  1.43809414e+00],
       [-1.63505459e+01, -6.81044385e-02,  1.16933548e+00,
         1.17541265e+00,  2.59239483e+00]], shape=(20000, 5)), 'train': array([[ 2.43452225e+01, -7.24347308e-02,  1.23010910e+00,
         2.66968441e+00,  2.97802305e+00],
       [ 2.33715572e+01,  8.99118707e-02,  2.21813297e+00,
         1.20959222e+00,  2.09908938e+00],
       [-1.18772745e+00,  2.82837935e-02,  1.26678193e+00,
         2.48928094e+00,  1.56289458e+00],
       ...,
       [ 6.85458755e+00, -7.04168305e-02,  1.16030550e+00,
         2.12546992e+00,  2.07751894e+00],
       [ 8.32945703e+03, -1.41441569e-01,  2.58052969e+00,
         1.57347536e+00,  2.44384480e+00],
       [-5.07489204e+01,  8.89461637e-02,  1.89850497e+00,
         2.87059665e+00,  2.64502048e+00]], shape=(80000, 5))}, desc=None)

In [30]:
import nd2py as nd
from tqdm import tqdm
from sr_agent.utils import symbolic_acc, setup_logging

setup_logging()


for idx, row in tqdm(df_results.iterrows(), total=len(df_results)):
    for problem in problems:
        if row['equation_id'] == problem.equation_idx:
            break
    else:
        raise ValueError(f"Problem with equation_id {row['equation_id']} not found in loaded problems.")
    
    f_true = nd.parse(row['gt_expression'])
    f_pred = nd.parse(row['discovered_expression'])
    data = {var: problem.samples['train'][:, idx] for idx, var in enumerate(problem.symbols)}
    result = symbolic_acc(f_true, f_pred, data)
    df_results.loc[idx, 'symbolic_acc'] = result['symbolic_acc']
    print(f"Problem ID: {row['equation_id']}, Symbolic Accuracy: {result['symbolic_acc']}, Reason: {result['reason']}")

AttributeError: 'OutStream' object has no attribute 'reconfigure'

In [29]:
f_true, f_pred

(-c * sqrt(1 - m_0 ** 2 / m ** 2), -c * sqrt(1 - (m_0 / m) ** 2))